version: "3.7"
services:
  post-dev-migration:
    container_name: post-dev-migration
    image: flyway/flyway
    command: -url=jdbc:postgresql://gola-dev-db.cfmrudiius8m.ap-south-1.rds.amazonaws.com:5432/post -schemas=post -user=post -password=gola -connectRetries=60 migrate
    volumes:
      - ./database/.:/flyway/sql
      - test-volume:/test-volume
    networks:
      - gola-network

volumes:
  test-volume:
  post_dep:

networks:
  gola-network:
    name: gola-network
