version: "3.7"
services:
  gola-db:
    image: gola-db
    build:
      context: .
      dockerfile: infrastructure/Migrate.Dockerfile
    restart: always
    container_name: gola-db
    env_file:
      - docker-compose-local.env
    ports:
      - '3306:3306'
    volumes:
      - ./sql:/sql
      - gola-volume:/var/lib/mysql
    networks:
      - gola-network

  post-migration:
    container_name: post-migration
    image: flyway/flyway
    command: -url=jdbc:mysql://gola-db:3306/POST -schemas=POST -user=POST -password=gola -connectRetries=60 migrate
    volumes:
      - ./database/.:/flyway/sql
    depends_on:
      - gola-db
    networks:
      - gola-network

networks:
  gola-network:
    name: gola-network

volumes:
  gola-volume:
