version: "3.7"
services:
  post-test-migration:
    container_name: post-test-migration
    image: flyway/flyway
    command: -url=jdbc:postgresql://gola-db:5432/post_test -schemas=post_test -user=post_test -password=gola -connectRetries=60 migrate
    volumes:
      - ./database/.:/flyway/sql
      - test-volume:/test-volume
    networks:
      - gola-network

  post-test:
    image: gola05/gocoverage:1.8
    depends_on:
      - post-test-migration
    env_file:
      - ./docker-compose-test.env
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/inclusi-blog
    volumes:
      - type: volume
        source: post_dep
        target: /go
      - ./:/home/gola/post-api
      - ./configuration:/home/gola/configuration
      - test-volume:/test-volume
    working_dir: /home/gola
    entrypoint: ["/bin/bash", "-c", "./testAndCover.sh -t=70 -pp=post-api"]

volumes:
  test-volume:
  post_dep:

networks:
  gola-network:
    name: gola-network
