version: "3.7"
services:
  post-test-migration:
    container_name: post-test-migration
    image: gola05/liquigraph:latest
    volumes:
      - ./database:/home/gola/database
    command: --changelog /home/gola/database/changelog.xml --username gola_admin_test --password gola --database golatest --graph-db-uri jdbc:neo4j:bolt://gola-db:7687/
    networks:
      - gola-network

  post-test:
    image: gola05/gocoverage:1.8
    depends_on:
      - post-test-migration
    env_file:
      - ./docker-compose-test.env
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/gola-glitch
    volumes:
      - type: volume
        source: post_dep
        target: /go
      - ./:/home/gola/post-api
      - ./configuration:/home/gola/configuration
      - test-volume:/test-volume
    working_dir: /home/gola
    entrypoint: ["/bin/bash", "-c", "./testAndCover.sh -t=70 -pp=post-api"]

volumes:
  test-volume:
  post_dep:

networks:
  gola-network:
    name: gola-network
