version: "3.7"
services:
  gola-db:
    image: gola-db
    restart: always
    container_name: gola-db
    env_file:
      - docker-compose-local.env
    ports:
      - '3306:3306'
    volumes:
      - gola-volume:/var/lib/mysql
    networks:
      - gola-network

networks:
  gola-network:
    name: gola-network

volumes:
  gola-volume:
