version: "3.7"
services:
  gola-db:
    image: postgres:latest
    restart: always
    container_name: gola-db
    env_file:
      - docker-compose-local.env
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/sql
      - gola-volume:/var/lib/mysql
    networks:
      - gola-network

  post-migration:
    container_name: post-migration
    image: post-migration
    build:
      context: .
      dockerfile: infrastructure/Migrate.Dockerfile
    command: -url=jdbc:postgresql://gola-db:5432/post -schemas=post -user=post -password=gola -connectRetries=60 migrate
    depends_on:
      - gola-db
    networks:
      - gola-network

  hydra-migrate:
    image: oryd/hydra:v1.10.5
    environment:
      - DSN=postgres://hydra:secret@gola-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - gola-db
    networks:
      - gola-network

  hydra:
    image: oryd/hydra:v1.10.5
    environment:
      - DSN=postgres://hydra:secret@gola-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - gola-db
    networks:
      - gola-network

networks:
  gola-network:
    name: gola-network

volumes:
  gola-volume:
