version: '3.7'
services:

  build-env:
    image: golang:1.18.8-alpine3.16
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/inclusi-blog
    platform: linux/amd64
    volumes:
      - type: volume
        source: post_dep
        target: /go
      - type: bind
        source: ../
        target: /post-api
    working_dir: /post-api

volumes:
  post_dep:
