# Default values for post-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gola05/post-api
  version: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: artifactory-registry

service:
  port: 8080
  targetPort: 8080

resources:
  requests:
    memory: "500Mi"
    cpu: "500m"
  limits:
    memory: "500Mi"
    cpu: "500m"

pdb:
  minAvailable: 1

hpa:
  minReplicas: 1
  maxReplicas: 2
  averageValue: 4

annotations:
  linkerd: enabled
  reloader:
    enabled: true
    configmap: true
    secret: true

configMountPath: "/configuration/config.json"

ingress:
    path: "/api/post"
    appFqdns:
      - "api.narratenet.com"
    allowedOrigins: app.narratenet.com|www.narratenet.com|narratenet.com|localhost:3000|localhost3001

livenessProbe:
  httpGet:
    path: "/api/post/healthz"

readinessProbe:
  httpGet:
    path: "/api/post/healthz"

database:
  name: "$DB_NAME"
  user: "$DB_USER"

global:
  Pipeline: "$ENV"

